"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from celery.schedules import crontab
import re
from pathlib import Path

import kombu

import sentry_sdk

from environ import Env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = Env()
env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", default="django-insecure-CHANGE_ME")

if env.str("SENTRY_DSN", default=""):
    sentry_sdk.init(
        dsn=env.str("SENTRY_DSN"),
        send_default_pii=env.bool("SENTRY_SEND_DEFAULT_PII", default=True),
        traces_sample_rate=env.float("SENTRY_TRACES_SAMPLE_RATE", default=0.1),
        environment=env.str("ENVIORNMENT", default="develop"),
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django_celery_results",
    "django_celery_beat",
    "health_check",
    "conf",
    "abst",
    "charts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db(
        default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": env.str("S3_ACCESS_KEY_ID", default=""),
            "secret_key": env.str("S3_SECRET_ACCESS_KEY", default=""),
            "bucket_name": env.str("S3_BUCKET_NAME", default=""),
            "querystring_auth": True,
            "file_overwrite": True,
            "region_name": env.str("S3_REGION_NAME", default="us-east-1"),
            "endpoint_url": env.str("S3_ENDPOINT_URL", ""),
            # "custom_domain": env.str("S3_DOMAIN", ""),
            "addressing_style": "auto",
        },
    },

    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = env.str("LANGUAGE_CODE", default="en-us")

TIME_ZONE = env.str("TIME_ZONE", default="UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "static/"


def immutable_file_test(_, url):
    """Determine if file is immutable and should be cached forever."""
    # Match vite (rollup)-generated hashes, à la, `some_file-CSliV9zW.js`
    return re.match(r"^.+[.-][0-9a-zA-Z_-]{8,12}\..+$", url)


WHITENOISE_IMMUTABLE_FILE_TEST = immutable_file_test
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REDIS_USER = env.str("REDIS_USER", default="default")
REDIS_PASSWORD = env.str("REDIS_PASSWORD", default="password")

REDIS_HOST = env.str("REDIS_HOST", default="redis")
REDIS_PORT = env.int("REDIS_PORT", default=6379)

REDIS_URL = f"redis://{REDIS_USER}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL + "/0",
    }
}

CELERY_BROKER_URL = REDIS_URL + "/1"

CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_RESULT_EXTENDED = True
CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24 * 30


CELERY_TASK_QUEUES = [kombu.Queue("celery")]


HEALTH_CHECK = {
    "DISK_USAGE_MAX": 90,
    "MEMORY_MIN": 100,  # in MB
    "SUBSETS": {
        "startup-probe": ["MigrationsHealthCheck", "DatabaseBackend"],
        "liveness-probe": ["DatabaseBackend"],
    },
}


UNFOLD = {
    "SITE_TITLE": "Administration",
    "SITE_HEADER": "Abstimmungsstudio",
    "SITE_SUBHEADER": "digital/organizing",
    "SITE_SYMBOL": "how_to_vote",
    "SHOW_LANGUAGES": False,
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "command_search": True,
        "show_all_applications": True,
    },
    "COMMAND": {
        "search_models": True,  # Search models in command search
    },
    "COLORS": {
        "base": {
            "50": "oklch(98.5% .002 247.839)",
            "100": "oklch(96.7% .003 264.542)",
            "200": "oklch(92.8% .006 264.531)",
            "300": "oklch(87.2% .01 258.338)",
            "400": "oklch(70.7% .022 261.325)",
            "500": "oklch(55.1% .027 264.364)",
            "600": "oklch(44.6% .03 256.802)",
            "700": "oklch(37.3% .034 259.733)",
            "800": "oklch(27.8% .033 256.848)",
            "900": "oklch(21% .034 264.665)",
            "950": "oklch(13% .028 261.692)",
        },
        "primary": {
            "50": "oklch(98.2% .024 99.57)",
            "100": "oklch(96.1% .055 99.84)",
            "200": "oklch(92.3% .105 100.24)",
            "300": "oklch(87.5% .156 99.87)",
            "400": "oklch(81.8% .178 97.89)",
            "500": "oklch(76.7% .159 95.71)",
            "600": "oklch(68.2% .136 92.48)",
            "700": "oklch(56.8% .113 88.67)",
            "800": "oklch(48.9% .096 85.32)",
            "900": "oklch(42.1% .081 82.94)",
            "950": "oklch(32.4% .063 81.26)",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },
}

INFLUX_URL = env.str("INFLUX_URL", default="")
INFLUX_TOKEN = env.str("INFLUX_TOKEN", default="")
INFLUX_ORG = env.str("INFLUX_ORG", default="")
INFLUX_BUCKET = env.str("INFLUX_BUCKET", default="")

CELERY_BEAT_SCHEDULE = {
    'fetch-active-votes-every-minute': {
        'task': 'abst.tasks.fetch_active_votes',
        'schedule': crontab(minute='*/1'),
    },
}
