# Generated by Django 6.0.3 on 2026-03-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeoStand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Kanton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short", models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vorlage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vorlagen_id", models.IntegerField(unique=True)),
                ("finished", models.BooleanField(default=False)),
                ("doppeltes_mehr", models.BooleanField(default=False)),
                ("angenommen", models.BooleanField(default=False)),
                ("ja_staende", models.FloatField(default=0)),
                ("nein_staende", models.FloatField(default=0)),
                ("result", models.JSONField(blank=True, null=True)),
                ("kantonal", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Gemeinde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("geo_id", models.IntegerField()),
                ("kanton", models.CharField(max_length=255)),
                (
                    "stand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="abst.geostand"
                    ),
                ),
            ],
            options={
                "ordering": ["geo_id"],
                "unique_together": {("geo_id", "stand")},
            },
        ),
        migrations.CreateModel(
            name="Abstimmungstag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("url_eidg", models.URLField(blank=True, null=True)),
                ("url_kantonal", models.URLField(blank=True, null=True)),
                (
                    "projection",
                    models.FileField(blank=True, null=True, upload_to="projections/"),
                ),
                (
                    "stand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="abst.geostand"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zaehlkreis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("geo_id", models.IntegerField()),
                (
                    "gemeinde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="abst.gemeinde"
                    ),
                ),
            ],
            options={
                "ordering": ["geo_id"],
                "unique_together": {("geo_id",)},
            },
        ),
    ]
