# Generated by Django 6.0.3 on 2026-03-06 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abst", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vorlage",
            name="related",
            field=models.ManyToManyField(blank=True, to="abst.vorlage"),
        ),
        migrations.AddField(
            model_name="vorlage",
            name="tag",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vorlagen",
                to="abst.abstimmungstag",
            ),
            preserve_default=False,
        ),
    ]
