# Generated by Django 6.0.3 on 2026-03-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abst", "0002_vorlage_related_vorlage_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="geostand",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="geostands/"),
        ),
    ]
