# Generated by Django 6.0.3 on 2026-03-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abst", "0003_geostand_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="vorlage",
            name="region",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
