# Generated by Django 6.0.3 on 2026-03-06 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("abst", "0004_vorlage_region"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="zaehlkreis",
            unique_together=set(),
        ),
    ]
