# Generated by Django 6.0.3 on 2026-03-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abst", "0005_alter_zaehlkreis_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="gemeinde",
            name="kanton_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kanton",
            name="kanton_id",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
