# Generated by Django 6.0.3 on 2026-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abst", "0006_gemeinde_kanton_id_kanton_kanton_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kanton",
            name="short",
            field=models.CharField(max_length=2),
        ),
    ]
