# Generated by Django 6.0.3 on 2026-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abst", "0007_alter_kanton_short"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstimmungstag",
            name="projection_bet",
            field=models.FileField(blank=True, null=True, upload_to="projections/"),
        ),
    ]
