# Generated by Django 6.0.3 on 2026-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abst", "0008_abstimmungstag_projection_bet"),
    ]

    operations = [
        migrations.AddField(
            model_name="kanton",
            name="lang_code",
            field=models.CharField(default="de", max_length=2),
        ),
    ]
