# Generated by Django 6.0.3 on 2026-03-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abst", "0009_kanton_lang_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abstimmungstag",
            name="name",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="vorlage",
            name="name",
            field=models.CharField(max_length=1024),
        ),
    ]
