# Generated by Django 6.0.3 on 2026-03-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abst", "0010_alter_abstimmungstag_name_alter_vorlage_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vorlage",
            options={"ordering": ["-vorlagen_id"]},
        ),
        migrations.AddField(
            model_name="vorlage",
            name="has_zk",
            field=models.BooleanField(default=False),
        ),
    ]
