# Generated by Django 6.0.3 on 2026-03-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abst", "0011_alter_vorlage_options_vorlage_has_zk"),
    ]

    operations = [
        migrations.AddField(
            model_name="kanton",
            name="stimmen",
            field=models.IntegerField(default=2),
        ),
    ]
