# Generated by Django 6.0.3 on 2026-06-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abst", "0013_partei"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionEvaluationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("num_votes", models.IntegerField()),
                ("vote_ids", models.JSONField()),
                ("steps_data", models.JSONField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
