# Generated by Django 6.0.3 on 2026-09-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abst', '0014_predictionevaluationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=64)),
                ('severity', models.IntegerField(default=1)),
                ('summary', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('posted', 'Gepostet'), ('dismissed', 'Verworfen')], default='pending', max_length=16)),
                ('dismiss_reason', models.CharField(blank=True, default='', max_length=512)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('vorlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_events', to='abst.vorlage')),
            ],
            options={
                'ordering': ['-severity', '-detected_at'],
                'unique_together': {('vorlage', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TickerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(default='agent', max_length=64)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vorlage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticker_notes', to='abst.vorlage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TickerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('published', 'Publiziert'), ('retracted', 'Zurückgezogen')], default='published', max_length=16)),
                ('author', models.CharField(default='agent', max_length=64)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('edited_by', models.CharField(blank=True, default='', max_length=64)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='ticker.tickerevent')),
                ('vorlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_posts', to='abst.vorlage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TickerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='live', max_length=16)),
                ('vorlage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_state', to='abst.vorlage')),
            ],
        ),
    ]
